# Generated by Django 4.2.14 on 2024-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
