# Generated by Django 4.2.14 on 2024-08-12 08:30

from django.db import migrations, models
import garbageapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Enter a 10-digit phone number', max_length=10, validators=[garbageapp.models.validate_phone_number]),
        ),
    ]
