# Generated by Django 4.2.14 on 2024-08-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0007_booking_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plant',
        ),
    ]
