# Generated by Django 4.2.14 on 2024-08-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0008_remove_booking_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garbageapp.plant'),
        ),
    ]
