# Generated by Django 4.2.14 on 2024-08-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0010_garbage_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='last_login',
        ),
    ]
