# Generated by Django 4.2.14 on 2024-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0011_remove_garbage_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbage',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
