# Generated by Django 4.2.14 on 2024-08-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0014_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
