# Generated by Django 4.2.14 on 2024-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbage',
            name='security_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garbage',
            name='security_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
