# Generated by Django 4.2.14 on 2024-08-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0017_garbage_security_answer_garbage_security_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbage',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='garbage',
            name='security_question',
        ),
    ]
